-- CREATING SQL USER FOR CI/CD PIPELINE MIGRATIONS APPLYING
GO;
BEGIN TRAN
-- create user for server
	CREATE LOGIN cicdUser WITH PASSWORD = '';
-- associate login with specific databaes
	USE [Blog];
	CREATE USER cicdUser FOR LOGIN cicdUser;
-- granting DDLpermissions to specific schema
	GRANT EXECUTE TO cicdUser
	GRANT ALTER ON SCHEMA::dbo TO cicdUser;
	GRANT CREATE TABLE TO cicdUser;
	GRANT CREATE VIEW TO cicdUser;
	GRANT CREATE PROCEDURE TO cicdUser;
	GRANT VIEW DEFINITION TO cicdUser;
	GRANT SELECT ON SCHEMA::dbo TO ciCdUser;
	GRANT UPDATE ON SCHEMA::dbo TO ciCdUser;
	GRANT INSERT ON SCHEMA::dbo TO ciCdUser;
	GRANT DELETE ON SCHEMA::dbo TO ciCdUser;
ROLLBACK;
--COMMIT;
GO;

--  REVOKE PERMISSIONS AND DELETING USER
GO;
BEGIN TRAN;
	USE [Blog];
	REVOKE SELECT TO cicdUser;
	REVOKE EXECUTE TO cicdUser;
	REVOKE ALTER ON SCHEMA::dbo TO cicdUser;
	REVOKE CREATE TABLE TO cicdUser;
	REVOKE CREATE VIEW TO cicdUser;
	REVOKE CREATE PROCEDURE TO cicdUser;
	REVOKE VIEW DEFINITION TO cicdUser;
	REVOKE SELECT ON SCHEMA::dbo TO ciCdUser;
	REVOKE UPDATE ON SCHEMA::dbo TO ciCdUser;
	REVOKE INSERT ON SCHEMA::dbo TO ciCdUser;
	REVOKE DELETE ON SCHEMA::dbo TO ciCdUser;
	DROP USER cicdUser;
	DROP LOGIN cicdUser;
ROLLBACK;
--COMMIT;
GO;
