version: '3.8'

services:
  redis:
    container_name: "Redis"
    restart: always
    image: "redis:7.2.3"
    ports:
      - "6379:6379"

  mssql:
    container_name: "mssql2022"
    restart: always
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      SA_PASSWORD: "P@ssword!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  rabbitmq:
    container_name: blog-mq
    restart: always
    hostname: blog-mq
    image: masstransit/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./.containers/queue/data/:/var/lib/rabbitmq/mnesia
      - ./.containers/queue/log/:/var/log/rabbitmq/mnesia
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    restart: always
    hostname: azurite
    command: "azurite --blobHost 127.0.0.1 --blobPort 10000 --queueHost 127.0.0.1 --queuePort 10001"
    ports:
      - "10000:10000"
      - "10001:10001"