name: Deploy React Application To GitHubActions

on:
  push:
    branches: [ "slave" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.11.0]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: React/my-blog/package-lock.json

    - name: Install dependencies
      run: npm --prefix React/my-blog install

    - name: Run tests
      run: npm --prefix React/my-blog test -- --coverage --passWithNoTests

    - name: Build
      env:
          CI: false
      run: npm --prefix React/my-blog run build

    - name: 'Create dotenv file'
      run: |
        cd React/my-blog
        touch .env
        echo REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }} >> .env
        cat .env

    - name: Deploy with GitHub Pages
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npm run deploy -- -u "github-actions-bot <support+actions@github.com>"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}