name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - slave

jobs:
  build_and_deploy_job:
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    env:
      CI: false
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Create dotenv file
        run: |
           cd React/my-blog
           ls -l
           touch .env
           echo -n REACT_APP_API_URL=${{ secrets.REACT_APP_API_URL }} > .env
           cat .env
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_HAPPY_OCEAN_0085BB803 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "/React/my-blog"
          output_location: "build"